//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("LuongID")]
    public partial class Bangluong : XPObject
    {
        string fNhanvien_ID;
        public string Nhanvien_ID
        {
            get { return fNhanvien_ID; }
            set { SetPropertyValue<string>(nameof(Nhanvien_ID), ref fNhanvien_ID, value); }
        }
        string fNam;
        public string Nam
        {
            get { return fNam; }
            set { SetPropertyValue<string>(nameof(Nam), ref fNam, value); }
        }
        string fThang;
        public string Thang
        {
            get { return fThang; }
            set { SetPropertyValue<string>(nameof(Thang), ref fThang, value); }
        }
        string fSogio;
        public string Sogio
        {
            get { return fSogio; }
            set { SetPropertyValue<string>(nameof(Sogio), ref fSogio, value); }
        }
        string fLuong;
        public string Luong
        {
            get { return fLuong; }
            set { SetPropertyValue<string>(nameof(Luong), ref fLuong, value); }
        }
    }

}
