//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("LuongID")]
    public partial class Bangluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"BangluongReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        int fNam;
        public int Nam
        {
            get { return fNam; }
            set { SetPropertyValue<int>(nameof(Nam), ref fNam, value); }
        }
        int fThang;
        public int Thang
        {
            get { return fThang; }
            set { SetPropertyValue<int>(nameof(Thang), ref fThang, value); }
        }
        decimal fSogio;
        public decimal Sogio
        {
            get { return fSogio; }
            set { SetPropertyValue<decimal>(nameof(Sogio), ref fSogio, value); }
        }
        [PersistentAlias("[Hesoluong] * [Sogio]")]
        public decimal Luong
        {
            get { return (decimal)(EvaluateAlias(nameof(Luong))); }
        }
        decimal fHesoluong;
        public decimal Hesoluong
        {
            get { return fHesoluong; }
            set { SetPropertyValue<decimal>(nameof(Hesoluong), ref fHesoluong, value); }
        }
    }

}
