//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    public partial class ChamCong : XPObject
    {
        string fNhanVien_ID;
        public string NhanVien_ID
        {
            get { return fNhanVien_ID; }
            set { SetPropertyValue<string>(nameof(NhanVien_ID), ref fNhanVien_ID, value); }
        }
        string fGiovao;
        public string Giovao
        {
            get { return fGiovao; }
            set { SetPropertyValue<string>(nameof(Giovao), ref fGiovao, value); }
        }
        string fGiora;
        public string Giora
        {
            get { return fGiora; }
            set { SetPropertyValue<string>(nameof(Giora), ref fGiora, value); }
        }
    }

}
