//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{
   
    [DefaultProperty("DinhluongID")]
    public partial class Dinhluong : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fDinhluongID;
        public string DinhluongID
        {
            get { return fDinhluongID; }
            set { SetPropertyValue<string>(nameof(DinhluongID), ref fDinhluongID, value); }
        }
        Sanpham fSanphamID;
        [Association(@"DinhluongReferencesSanpham")]
        public Sanpham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<Sanpham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        Sanpham fThanhphanID;
        [Association(@"DinhluongReferencesSanpham1")]
        public Sanpham ThanhphanID
        {
            get { return fThanhphanID; }
            set { SetPropertyValue<Sanpham>(nameof(ThanhphanID), ref fThanhphanID, value); }
        }
        int fSoluong;
        public int Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<int>(nameof(Soluong), ref fSoluong, value); }
        }
    }

}
