//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("DongID")]
    public partial class Dongnhap : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fDongID;
        public string DongID
        {
            get { return fDongID; }
            set { SetPropertyValue<string>(nameof(DongID), ref fDongID, value); }
        }
        Sanpham fTenSP;
        [Association(@"DongnhapReferencesSanpham")]
        public Sanpham TenSP
        {
            get { return fTenSP; }
            set { SetPropertyValue<Sanpham>(nameof(TenSP), ref fTenSP, value); }
        }
        Phieunhap fNhap_ID;
        [Association(@"DongnhapReferencesPhieunhap")]
        public Phieunhap Nhap_ID
        {
            get { return fNhap_ID; }
            set { SetPropertyValue<Phieunhap>(nameof(Nhap_ID), ref fNhap_ID, value); }
        }
        int fSoluong;
        public int Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<int>(nameof(Soluong), ref fSoluong, value); }
        }
        int fDongia;
        public int Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<int>(nameof(Dongia), ref fDongia, value); }
        }
    }

}
