//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("DongID")]
    public partial class Dongnhap : XPObject
    {
        string fSanpham_ID;
        public string Sanpham_ID
        {
            get { return fSanpham_ID; }
            set { SetPropertyValue<string>(nameof(Sanpham_ID), ref fSanpham_ID, value); }
        }
        string fNhap_ID;
        public string Nhap_ID
        {
            get { return fNhap_ID; }
            set { SetPropertyValue<string>(nameof(Nhap_ID), ref fNhap_ID, value); }
        }
        string fSoluong;
        public string Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<string>(nameof(Soluong), ref fSoluong, value); }
        }
        string fDongia;
        public string Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<string>(nameof(Dongia), ref fDongia, value); }
        }
    }

}
