//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
using DevExpress.Persistent.Base;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("Soban")]
    [DefaultClassOptions]
    public partial class Hoadon : DevExpress.Persistent.BaseImpl.BaseObject
    {
        int fSoban;
        [DevExpress.Xpo.DisplayName(@"số bàn")]
        public int Soban
        {
            get { return fSoban; }
            set { SetPropertyValue<int>(nameof(Soban), ref fSoban, value); }
        }
        DateTime fNgay;
        [DevExpress.Xpo.DisplayName(@"Ngày")]
        [DevExpress.ExpressApp.Model.ModelDefault("EditMask", "dd/MM/yyyy HH:mm"),
DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "{0:dd/MM/yyyy HH:mm}")]
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        int fSophieu;
        [DevExpress.Persistent.Validation.RuleUniqueValue]
        public int Sophieu
        {
            get { return fSophieu; }
            set { SetPropertyValue<int>(nameof(Sophieu), ref fSophieu, value); }
        }
        [DevExpress.Xpo.DisplayName(@"Tổng tiền")]
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###")]

        public decimal Tongtien
        {
            get
            {
                decimal tien = 0;
                foreach(HoadonCT item in HoadonCTs)
                {
                    tien += item.Thanhtien;
                }
                return tien;
            }
        }
        [Association(@"HoadonCTReferencesHoadon"), Aggregated]
        public XPCollection<HoadonCT> HoadonCTs { get { return GetCollection<HoadonCT>(nameof(HoadonCTs)); } }
    }

}
