//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("HoadonCTID")]
    public partial class HoadonCT : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fHoadonID;
        public string HoadonID
        {
            get { return fHoadonID; }
            set { SetPropertyValue<string>(nameof(HoadonID), ref fHoadonID, value); }
        }
        Sanpham fSanphamID;
        [Association(@"HoadonCTReferencesSanpham")]
        public Sanpham SanphamID
        {
            get { return fSanphamID; }
            set { SetPropertyValue<Sanpham>(nameof(SanphamID), ref fSanphamID, value); }
        }
        double fSoluong;
        public double Soluong
        {
            get { return fSoluong; }
            set { SetPropertyValue<double>(nameof(Soluong), ref fSoluong, value); }
        }
        decimal fDongia;
        public decimal Dongia
        {
            get { return fDongia; }
            set { SetPropertyValue<decimal>(nameof(Dongia), ref fDongia, value); }
        }
        [PersistentAlias("ToDecimal([Soluong]) * [Dongia]")]
        public decimal Thanhtien
        {
            get { return (decimal)(EvaluateAlias(nameof(Thanhtien))); }
        }
        Hoadon fHoadonCTID;
        [Association(@"HoadonCTReferencesHoadon")]
        public Hoadon HoadonCTID
        {
            get { return fHoadonCTID; }
            set { SetPropertyValue<Hoadon>(nameof(HoadonCTID), ref fHoadonCTID, value); }
        }
        [Association(@"TieuhaoReferencesHoadonCT"), Aggregated]
        public XPCollection<Tieuhao> Tieuhaos { get { return GetCollection<Tieuhao>(nameof(Tieuhaos)); } }
    }

}
