//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("KhachhangID")]
    public partial class Khachhang : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fKhachhangID;
        public string KhachhangID
        {
            get { return fKhachhangID; }
            set { SetPropertyValue<string>(nameof(KhachhangID), ref fKhachhangID, value); }
        }
        string fHoten;
        public string Hoten
        {
            get { return fHoten; }
            set { SetPropertyValue<string>(nameof(Hoten), ref fHoten, value); }
        }
        int fSodienthoai;
        public int Sodienthoai
        {
            get { return fSodienthoai; }
            set { SetPropertyValue<int>(nameof(Sodienthoai), ref fSodienthoai, value); }
        }
        [Association(@"HoadonReferencesKhachhang"), Aggregated]
        public XPCollection<Hoadon> Hoadons { get { return GetCollection<Hoadon>(nameof(Hoadons)); } }
    }

}
