//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("NhanvienID")]
    public partial class Nhanvien : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhanvienID;
        public string NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<string>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        string fHoten;
        public string Hoten
        {
            get { return fHoten; }
            set { SetPropertyValue<string>(nameof(Hoten), ref fHoten, value); }
        }
        int fSodienthoai;
        public int Sodienthoai
        {
            get { return fSodienthoai; }
            set { SetPropertyValue<int>(nameof(Sodienthoai), ref fSodienthoai, value); }
        }
        double fMucluong;
        public double Mucluong
        {
            get { return fMucluong; }
            set { SetPropertyValue<double>(nameof(Mucluong), ref fMucluong, value); }
        }
        [Association(@"ChamcongReferencesNhanvien"), Aggregated]
        public XPCollection<Chamcong> Chamcongs { get { return GetCollection<Chamcong>(nameof(Chamcongs)); } }
        [Association(@"HoadonReferencesNhanvien"), Aggregated]
        public XPCollection<Hoadon> Hoadons { get { return GetCollection<Hoadon>(nameof(Hoadons)); } }
    }

}
