//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    public partial class NhomSP : DevExpress.Persistent.BaseImpl.BaseObject
    {
        string fNhom_ID;
        public string Nhom_ID
        {
            get { return fNhom_ID; }
            set { SetPropertyValue<string>(nameof(Nhom_ID), ref fNhom_ID, value); }
        }
        string fTennhom;
        public string Tennhom
        {
            get { return fTennhom; }
            set { SetPropertyValue<string>(nameof(Tennhom), ref fTennhom, value); }
        }
        string fPhanloai;
        public string Phanloai
        {
            get { return fPhanloai; }
            set { SetPropertyValue<string>(nameof(Phanloai), ref fPhanloai, value); }
        }
    }

}
