//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    [DefaultProperty("ChiID")]
    public partial class Phieuchi : DevExpress.Persistent.BaseImpl.BaseObject
    {
        Nhanvien fNhanvienID;
        [Association(@"PhieuchiReferencesNhanvien")]
        public Nhanvien NhanvienID
        {
            get { return fNhanvienID; }
            set { SetPropertyValue<Nhanvien>(nameof(NhanvienID), ref fNhanvienID, value); }
        }
        string fNCC_ID;
        public string NCC_ID
        {
            get { return fNCC_ID; }
            set { SetPropertyValue<string>(nameof(NCC_ID), ref fNCC_ID, value); }
        }
        string fSo;
        public string So
        {
            get { return fSo; }
            set { SetPropertyValue<string>(nameof(So), ref fSo, value); }
        }
        DateTime fNgay;
        public DateTime Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<DateTime>(nameof(Ngay), ref fNgay, value); }
        }
        decimal fSotien;
        [DevExpress.ExpressApp.Model.ModelDefault("DisplayFormat", "### ### ### ###"),
DevExpress.ExpressApp.Model.ModelDefault("EditMask", "### ### ### ###")]
        public decimal Sotien
        {
            get { return fSotien; }
            set { SetPropertyValue<decimal>(nameof(Sotien), ref fSotien, value); }
        }
    }

}
