//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using DevExpress.Xpo;
using DevExpress.Xpo.Metadata;
using DevExpress.Data.Filtering;
using System.Collections.Generic;
using System.ComponentModel;
using System.Reflection;
namespace Cafeshop.Module.ORMDataModel1
{

    public partial class Phieunhap : XPObject
    {
        string fNhap_ID;
        public string Nhap_ID
        {
            get { return fNhap_ID; }
            set { SetPropertyValue<string>(nameof(Nhap_ID), ref fNhap_ID, value); }
        }
        string fNCC_ID;
        public string NCC_ID
        {
            get { return fNCC_ID; }
            set { SetPropertyValue<string>(nameof(NCC_ID), ref fNCC_ID, value); }
        }
        string fNhanvien_ID;
        public string Nhanvien_ID
        {
            get { return fNhanvien_ID; }
            set { SetPropertyValue<string>(nameof(Nhanvien_ID), ref fNhanvien_ID, value); }
        }
        string fSo;
        public string So
        {
            get { return fSo; }
            set { SetPropertyValue<string>(nameof(So), ref fSo, value); }
        }
        string fNgay;
        public string Ngay
        {
            get { return fNgay; }
            set { SetPropertyValue<string>(nameof(Ngay), ref fNgay, value); }
        }
    }

}
